baseURL: https://sailing-and-coaching.netlify.app/
disableKinds:
  - section
  - taxonomy
  - term
  - RSS
  - robotsTXT
defaultContentLanguage: en
theme: hugo-scroll
title: Sailcoaching
params:
  copyright: © Oliver Gansser
  description: Sailing & Coaching
  favicon: images/favicon.png
  images: images/cover-image.jpg
  meta:
    keywords: coaching, Sailing
  title: Sailcoaching
